module.exports.craftN = [
    'Just Craftin\' Around',
    'Anything Goes',    
    'Out of the Box',
    'iCandy',    
    'Craft n\' Creations',
    'Knotty Knitters',
    'Handy Mandy',    
    'Dreamy Designs',
    'TwoCan',   
    'Craftastic   ', 
    'Sunnyside Keepsakes',    
    'Hot Hands Crafts',    
    'CraftWorks',    
    'Happy Crafts',   
    'The Scrap Shop',
    'Crafts Unthreaded',    
    'Kiddy Krafts',   
    'That\'s Crafty!',    
    'Crafterina',    
    'Dreamation Designs',    
    'The Craft House',   
    'Craft Machine',    
    'Little Rosebud',    
    'Smart Art Crafts',    
    'Clip n\' Snip',
    'The Art Box',    
    'Buttons and Bows',    
    'The Kraft Lady',    
    'Craft Angels',        
    'Heavenly Handmade',    
    'Greenlight Creations',    
    'Craft Tree',    
    'Dyed in Heaven',    
    'Treehouse Crafts',    
    'Crazy Crafty Chicks',    
    'Curly Q\'s Creations',    
    'Susy Q\'s',    
    'Artsy Fartsy',    
    'LeftBrain Creations',    
    'MetalEdge Crafts',    
    'Junk Drawer Artisan'
]

module.exports.craftType = [
'Basket Weaving',
'Candle Making',
'Ceramic',
'Crochet',
'Decoupage',
'Doll Making',
'Embroidery',
'Felting',
'Ikebana',
'Knitting',
'Lace Making',
'Latch Hook Rugs',
'Leatherwork',
'Macrame',
'Make Miniature Models',
'Make Beaded Jewelry',
'Mosaics',
'Origami',
'Paper Making',
'Printmaking',
'Quilting',
'Soap Making',
'Stained Glass',
'Weaving',
'Wood Carving'
]